name: Security Audit
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-verison: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit
